---
- name: Install Nginx on Amazon Linux
  command: amazon-linux-extras install -y nginx1

- name: Copy Nginx config file with correct FPM socket
  ansible.builtin.copy:
    src: "default.conf"
    dest: /etc/nginx/conf.d
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: Restart Nginx

- name: Make nginx a service
  ansible.builtin.service:
    name: nginx
    enabled: yes

...
