---
- name: Enable PHP 8.0
  command: amazon-linux-extras enable php8.0

- name: Install PHP FPM and dependencies
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - "php"
    - "php-cli"
    - "php-mysqlnd"
    - "php-common"
    - "php-fpm"
    - "php-gd"
    - "php-mbstring"
    - "php-xml"
    - "php-dom"
    - "php-intl"
    - "php-simplexml"

- name: Copy FPM config file with correct FPM socket
  ansible.builtin.copy:
    src: "www.conf"
    dest: /etc/php-fpm.d/
    owner: root
    group: root
    mode: '0644'
    backup: yes
  
- name: Fix permissions for PHP sessions
  ansible.builtin.file:
    path: /var/lib/php/session
    owner: nginx
    group: nginx
  notify: Restart FPM

- name: Make FPM a service
  ansible.builtin.service:
    name: php-fpm
    enabled: yes
...